/*!
 * Zepto v1.0 zeptojs.com | MIT licensed
 * Modules: zepto, data, stack, polyfill, event, detect, fx, ajax, form
 */
var Zepto=function(){function b(a){return null==a?String(a):I[S.call(a)]||"object"}function k(a){return"function"==b(a)}function l(a){return null!=a&&a==a.window}function j(a){return null!=a&&a.nodeType==a.DOCUMENT_NODE}function m(a){return"object"==b(a)}function n(a){return m(a)&&!l(a)&&a.__proto__==Object.prototype}function q(a){return a instanceof Array}function C(a){return"number"==typeof a.length}function p(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,
"$1_$2").replace(/_/g,"-").toLowerCase()}function r(a){return a in J?J[a]:J[a]=RegExp("(^|\\s)"+a+"(\\s|$)")}function y(a){return"children"in a?w.call(a.children):d.map(a.childNodes,function(a){if(1==a.nodeType)return a})}function z(a,e,h){for(g in e)h&&(n(e[g])||q(e[g]))?(n(e[g])&&!n(a[g])&&(a[g]={}),q(e[g])&&!q(a[g])&&(a[g]=[]),z(a[g],e[g],h)):e[g]!==f&&(a[g]=e[g])}function A(a,e){return e===f?d(a):d(a).filter(e)}function x(a,e,h,d){return k(e)?e.call(a,h,d):e}function u(a,e){var h=a.className,
d=h&&h.baseVal!==f;if(e===f)return d?h.baseVal:h;d?h.baseVal=e:a.className=e}function F(a){var e;try{return a?"true"==a||("false"==a?!1:"null"==a?null:!isNaN(e=Number(a))?e:/^[\[\{]/.test(a)?d.parseJSON(a):a):a}catch(h){return a}}function c(a,e){e(a);for(var h in a.childNodes)c(a.childNodes[h],e)}var f,g,d,E,D=[],w=D.slice,t=D.filter,B=window.document,G={},J={},s=B.defaultView.getComputedStyle,M={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},N=/^\s*<(\w+|!)[^>]*>/,
T=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,O=/^(?:body|html)$/i,U="val css html text data width height offset".split(" "),K=B.createElement("table"),P=B.createElement("tr"),Q={tr:B.createElement("tbody"),tbody:K,thead:K,tfoot:K,td:P,th:P,"*":B.createElement("div")},V=/complete|loaded|interactive/,W=/^\.([\w-]+)$/,X=/^#([\w-]*)$/,Y=/^[\w-]+$/,I={},S=I.toString,v={},L,H,R=B.createElement("div");v.matches=function(a,e){if(!a||1!==a.nodeType)return!1;var h=a.webkitMatchesSelector||
a.mozMatchesSelector||a.oMatchesSelector||a.matchesSelector;if(h)return h.call(a,e);var d;d=a.parentNode;(h=!d)&&(d=R).appendChild(a);d=~v.qsa(d,e).indexOf(a);h&&R.removeChild(a);return d};L=function(a){return a.replace(/-+(.)?/g,function(a,h){return h?h.toUpperCase():""})};H=function(a){return t.call(a,function(e,h){return a.indexOf(e)==h})};v.fragment=function(a,e,h){a.replace&&(a=a.replace(T,"<$1></$2>"));e===f&&(e=N.test(a)&&RegExp.$1);e in Q||(e="*");var b,c=Q[e];c.innerHTML=""+a;a=d.each(w.call(c.childNodes),
function(){c.removeChild(this)});n(h)&&(b=d(a),d.each(h,function(a,e){if(-1<U.indexOf(a))b[a](e);else b.attr(a,e)}));return a};v.Z=function(a,e){a=a||[];a.__proto__=d.fn;a.selector=e||"";return a};v.isZ=function(a){return a instanceof v.Z};v.init=function(a,e){if(a){if(k(a))return d(B).ready(a);if(v.isZ(a))return a;var h;if(q(a))h=t.call(a,function(a){return null!=a});else if(m(a))h=[n(a)?d.extend({},a):a],a=null;else if(N.test(a))h=v.fragment(a.trim(),RegExp.$1,e),a=null;else{if(e!==f)return d(e).find(a);
h=v.qsa(B,a)}return v.Z(h,a)}return v.Z()};d=function(a,e){return v.init(a,e)};d.extend=function(a){var e,h=w.call(arguments,1);"boolean"==typeof a&&(e=a,a=h.shift());h.forEach(function(h){z(a,h,e)});return a};v.qsa=function(a,e){var h;return j(a)&&X.test(e)?(h=a.getElementById(RegExp.$1))?[h]:[]:1!==a.nodeType&&9!==a.nodeType?[]:w.call(W.test(e)?a.getElementsByClassName(RegExp.$1):Y.test(e)?a.getElementsByTagName(e):a.querySelectorAll(e))};d.contains=function(a,e){return a!==e&&a.contains(e)};d.type=
b;d.isFunction=k;d.isWindow=l;d.isArray=q;d.isPlainObject=n;d.isEmptyObject=function(a){for(var e in a)return!1;return!0};d.inArray=function(a,e,h){return D.indexOf.call(e,a,h)};d.camelCase=L;d.trim=function(a){return a.trim()};d.uuid=0;d.support={};d.expr={};d.map=function(a,e){var h,b=[],c;if(C(a))for(c=0;c<a.length;c++)h=e(a[c],c),null!=h&&b.push(h);else for(c in a)h=e(a[c],c),null!=h&&b.push(h);return 0<b.length?d.fn.concat.apply([],b):b};d.each=function(a,e){var h;if(C(a))for(h=0;h<a.length&&
!1!==e.call(a[h],h,a[h]);h++);else for(h in a)if(!1===e.call(a[h],h,a[h]))break;return a};d.grep=function(a,e){return t.call(a,e)};window.JSON&&(d.parseJSON=JSON.parse);d.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,e){I["[object "+e+"]"]=e.toLowerCase()});d.fn={forEach:D.forEach,reduce:D.reduce,push:D.push,sort:D.sort,indexOf:D.indexOf,concat:D.concat,map:function(a){return d(d.map(this,function(e,h){return a.call(e,h,e)}))},slice:function(){return d(w.apply(this,
arguments))},ready:function(a){V.test(B.readyState)?a(d):B.addEventListener("DOMContentLoaded",function(){a(d)},!1);return this},get:function(a){return a===f?w.call(this):this[0<=a?a:a+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&this.parentNode.removeChild(this)})},each:function(a){D.every.call(this,function(e,h){return!1!==a.call(e,h,e)});return this},filter:function(a){return k(a)?this.not(this.not(a)):
d(t.call(this,function(e){return v.matches(e,a)}))},add:function(a,e){return d(H(this.concat(d(a,e))))},is:function(a){return 0<this.length&&v.matches(this[0],a)},not:function(a){var e=[];if(k(a)&&a.call!==f)this.each(function(h){a.call(this,h)||e.push(this)});else{var h="string"==typeof a?this.filter(a):C(a)&&k(a.item)?w.call(a):d(a);this.forEach(function(a){0>h.indexOf(a)&&e.push(a)})}return d(e)},has:function(a){return this.filter(function(){return m(a)?d.contains(this,a):d(this).find(a).size()})},
eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];return a&&!m(a)?a:d(a)},last:function(){var a=this[this.length-1];return a&&!m(a)?a:d(a)},find:function(a){var e=this;return"object"==typeof a?d(a).filter(function(){var a=this;return D.some.call(e,function(e){return d.contains(e,a)})}):1==this.length?d(v.qsa(this[0],a)):this.map(function(){return v.qsa(this,a)})},closest:function(a,e){var h=this[0],b=!1;for("object"==typeof a&&(b=d(a));h&&!(b?0<=b.indexOf(h):
v.matches(h,a));)h=h!==e&&!j(h)&&h.parentNode;return d(h)},parents:function(a){for(var e=[],h=this;0<h.length;)h=d.map(h,function(a){if((a=a.parentNode)&&!j(a)&&0>e.indexOf(a))return e.push(a),a});return A(e,a)},parent:function(a){return A(H(this.pluck("parentNode")),a)},children:function(a){return A(this.map(function(){return y(this)}),a)},contents:function(){return this.map(function(){return w.call(this.childNodes)})},siblings:function(a){return A(this.map(function(a,h){return t.call(y(h.parentNode),
function(a){return a!==h})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return d.map(this,function(e){return e[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display=null);if("none"==s(this,"").getPropertyValue("display")){var a=this.style,e=this.nodeName,h,d;G[e]||(h=B.createElement(e),B.body.appendChild(h),d=s(h,"").getPropertyValue("display"),h.parentNode.removeChild(h),"none"==d&&(d="block"),G[e]=d);a.display=
G[e]}})},replaceWith:function(a){return this.before(a).remove()},wrap:function(a){var e=k(a);if(this[0]&&!e)var h=d(a).get(0),b=h.parentNode||1<this.length;return this.each(function(c){d(this).wrapAll(e?a.call(this,c):b?h.cloneNode(!0):h)})},wrapAll:function(a){if(this[0]){d(this[0]).before(a=d(a));for(var e;(e=a.children()).length;)a=e.first();d(a).append(this)}return this},wrapInner:function(a){var e=k(a);return this.each(function(h){var b=d(this),c=b.contents();h=e?a.call(this,h):a;c.length?c.wrapAll(h):
b.append(h)})},unwrap:function(){this.parent().each(function(){d(this).replaceWith(d(this).children())});return this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(a){return this.each(function(){var e=d(this);(a===f?"none"==e.css("display"):a)?e.show():e.hide()})},prev:function(a){return d(this.pluck("previousElementSibling")).filter(a||"*")},next:function(a){return d(this.pluck("nextElementSibling")).filter(a||
"*")},html:function(a){return a===f?0<this.length?this[0].innerHTML:null:this.each(function(e){var h=this.innerHTML;d(this).empty().append(x(this,a,e,h))})},text:function(a){return a===f?0<this.length?this[0].textContent:null:this.each(function(){this.textContent=a})},attr:function(a,e){var h;return"string"==typeof a&&e===f?0==this.length||1!==this[0].nodeType?f:"value"==a&&"INPUT"==this[0].nodeName?this.val():!(h=this[0].getAttribute(a))&&a in this[0]?this[0][a]:h:this.each(function(h){if(1===this.nodeType)if(m(a))for(g in a){h=
g;var d=a[g];null==d?this.removeAttribute(h):this.setAttribute(h,d)}else h=x(this,e,h,this.getAttribute(a)),null==h?this.removeAttribute(a):this.setAttribute(a,h)})},removeAttr:function(a){return this.each(function(){1===this.nodeType&&this.removeAttribute(a)})},prop:function(a,e){return e===f?this[0]&&this[0][a]:this.each(function(h){this[a]=x(this,e,h,this[a])})},data:function(a,e){var h=this.attr("data-"+p(a),e);return null!==h?F(h):f},val:function(a){return a===f?this[0]&&(this[0].multiple?d(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):
this[0].value):this.each(function(e){this.value=x(this,a,e,this.value)})},offset:function(a){if(a)return this.each(function(e){var b=d(this);e=x(this,a,e,b.offset());var c=b.offsetParent().offset();e={top:e.top-c.top,left:e.left-c.left};"static"==b.css("position")&&(e.position="relative");b.css(e)});if(0==this.length)return null;var e=this[0].getBoundingClientRect();return{left:e.left+window.pageXOffset,top:e.top+window.pageYOffset,width:Math.round(e.width),height:Math.round(e.height)}},css:function(a,
e){if(2>arguments.length&&"string"==typeof a)return this[0]&&(this[0].style[L(a)]||s(this[0],"").getPropertyValue(a));var d="";if("string"==b(a))!e&&0!==e?this.each(function(){this.style.removeProperty(p(a))}):d=p(a)+":"+("number"==typeof e&&!M[p(a)]?e+"px":e);else for(g in a)!a[g]&&0!==a[g]?this.each(function(){this.style.removeProperty(p(g))}):d+=p(g)+":"+("number"==typeof a[g]&&!M[p(g)]?a[g]+"px":a[g])+";";return this.each(function(){this.style.cssText+=";"+d})},index:function(a){return a?this.indexOf(d(a)[0]):
this.parent().children().indexOf(this[0])},hasClass:function(a){return D.some.call(this,function(a){return this.test(u(a))},r(a))},addClass:function(a){return this.each(function(e){E=[];var b=u(this);x(this,a,e,b).split(/\s+/g).forEach(function(a){d(this).hasClass(a)||E.push(a)},this);E.length&&u(this,b+(b?" ":"")+E.join(" "))})},removeClass:function(a){return this.each(function(e){if(a===f)return u(this,"");E=u(this);x(this,a,e,E).split(/\s+/g).forEach(function(a){E=E.replace(r(a)," ")});u(this,
E.trim())})},toggleClass:function(a,e){return this.each(function(b){var c=d(this);x(this,a,b,u(this)).split(/\s+/g).forEach(function(a){(e===f?!c.hasClass(a):e)?c.addClass(a):c.removeClass(a)})})},scrollTop:function(){if(this.length)return"scrollTop"in this[0]?this[0].scrollTop:this[0].scrollY},position:function(){if(this.length){var a=this[0],e=this.offsetParent(),b=this.offset(),c=O.test(e[0].nodeName)?{top:0,left:0}:e.offset();b.top-=parseFloat(d(a).css("margin-top"))||0;b.left-=parseFloat(d(a).css("margin-left"))||
0;c.top+=parseFloat(d(e[0]).css("border-top-width"))||0;c.left+=parseFloat(d(e[0]).css("border-left-width"))||0;return{top:b.top-c.top,left:b.left-c.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||B.body;a&&!O.test(a.nodeName)&&"static"==d(a).css("position");)a=a.offsetParent;return a})}};d.fn.detach=d.fn.remove;["width","height"].forEach(function(a){d.fn[a]=function(e){var b,c=this[0],t=a.replace(/./,function(a){return a[0].toUpperCase()});return e===f?l(c)?
c["inner"+t]:j(c)?c.documentElement["offset"+t]:(b=this.offset())&&b[a]:this.each(function(b){c=d(this);c.css(a,x(this,e,b,c[a]()))})}});["after","prepend","before","append"].forEach(function(a,e){var h=e%2;d.fn[a]=function(){var a,t=d.map(arguments,function(e){a=b(e);return"object"==a||"array"==a||null==e?e:v.fragment(e)}),f,w=1<this.length;return 1>t.length?this:this.each(function(a,b){f=h?b:b.parentNode;b=0==e?b.nextSibling:1==e?b.firstChild:2==e?b:null;t.forEach(function(a){if(w)a=a.cloneNode(!0);
else if(!f)return d(a).remove();c(f.insertBefore(a,b),function(a){null!=a.nodeName&&("SCRIPT"===a.nodeName.toUpperCase()&&(!a.type||"text/javascript"===a.type)&&!a.src)&&window.eval.call(window,a.innerHTML)})})})};d.fn[h?a+"To":"insert"+(e?"Before":"After")]=function(e){d(e)[a](this);return this}});v.Z.prototype=d.fn;v.uniq=H;v.deserializeValue=F;d.zepto=v;return d}();window.Zepto=Zepto;"$"in window||(window.$=Zepto);
(function(b){function k(k,p){var r=k[q],r=r&&j[r];if(void 0===p)return r||l(k);if(r){if(p in r)return r[p];var y=n(p);if(y in r)return r[y]}return m.call(b(k),p)}function l(l,k,m){var y=l[q]||(l[q]=++b.uuid),z;if(!(z=j[y])){z=j;var A={};b.each(l.attributes,function(l,j){0==j.name.indexOf("data-")&&(A[n(j.name.replace("data-",""))]=b.zepto.deserializeValue(j.value))});z=z[y]=A}l=z;void 0!==k&&(l[n(k)]=m);return l}var j={},m=b.fn.data,n=b.camelCase,q=b.expando="Zepto"+ +new Date;b.fn.data=function(j,
m){return void 0===m?b.isPlainObject(j)?this.each(function(k,m){b.each(j,function(b,j){l(m,b,j)})}):0==this.length?void 0:k(this[0],j):this.each(function(){l(this,j,m)})};b.fn.removeData=function(l){"string"==typeof l&&(l=l.split(/\s+/));return this.each(function(){var k=this[q],m=k&&j[k];m&&b.each(l,function(){delete m[n(this)]})})}})(Zepto);
(function(b){String.prototype.trim===b&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Array.prototype.reduce===b&&(Array.prototype.reduce=function(k){if(void 0===this||null===this)throw new TypeError;var l=Object(this),j=l.length>>>0,m=0,n;if("function"!=typeof k)throw new TypeError;if(0==j&&1==arguments.length)throw new TypeError;if(2<=arguments.length)n=arguments[1];else{do{if(m in l){n=l[m++];break}if(++m>=j)throw new TypeError;}while(1)}for(;m<j;)m in l&&(n=k.call(b,
n,l[m],m,l)),m++;return n})})();
(function(b){function k(b){return b._zid||(b._zid=r++)}function l(b,f,g,d){f=j(f);if(f.ns)var l=RegExp("(?:^| )"+f.ns.replace(" "," .* ?")+"(?: |$)");return(p[k(b)]||[]).filter(function(b){return b&&(!f.e||b.e==f.e)&&(!f.ns||l.test(b.ns))&&(!g||k(b.fn)===k(g))&&(!d||b.sel==d)})}function j(b){b=(""+b).split(".");return{e:b[0],ns:b.slice(1).sort().join(" ")}}function m(c,f,g){"string"!=b.type(c)?b.each(c,g):c.split(/\s/).forEach(function(b){g(b,f)})}function n(c,f,g,d,l,n){var w=k(c),t=p[w]||(p[w]=
[]);m(f,g,function(f,w){var g=j(f);g.fn=w;g.sel=d;g.e in z&&(w=function(d){var c=d.relatedTarget;if(!c||c!==this&&!b.contains(this,c))return g.fn.apply(this,arguments)});g.del=l&&l(w,f);var k=g.del||w;g.proxy=function(b){var d=k.apply(c,[b].concat(b.data));!1===d&&(b.preventDefault(),b.stopPropagation());return d};g.i=t.length;t.push(g);c.addEventListener(z[g.e]||g.e,g.proxy,g.del&&("focus"==g.e||"blur"==g.e)||!!n)})}function q(b,f,g,d,j){var n=k(b);m(f||"",g,function(f,t){l(b,f,t,d).forEach(function(d){delete p[n][d.i];
b.removeEventListener(z[d.e]||d.e,d.proxy,d.del&&("focus"==d.e||"blur"==d.e)||!!j)})})}function C(c){var f,g={originalEvent:c};for(f in c)!u.test(f)&&void 0!==c[f]&&(g[f]=c[f]);b.each(F,function(b,f){g[b]=function(){this[f]=A;return c[b].apply(c,arguments)};g[f]=x});return g}var p={},r=1,y={},z={mouseenter:"mouseover",mouseleave:"mouseout"};y.click=y.mousedown=y.mouseup=y.mousemove="MouseEvents";b.event={add:n,remove:q};b.proxy=function(c,f){if(b.isFunction(c)){var g=function(){return c.apply(f,arguments)};
g._zid=k(c);return g}if("string"==typeof f)return b.proxy(c[f],c);throw new TypeError("expected function");};b.fn.bind=function(b,f){return this.each(function(){n(this,b,f)})};b.fn.unbind=function(b,f){return this.each(function(){q(this,b,f)})};b.fn.one=function(b,f){return this.each(function(g,d){n(this,b,f,null,function(b,c){return function(){var f=b.apply(d,arguments);q(d,c,b);return f}})})};var A=function(){return!0},x=function(){return!1},u=/^([A-Z]|layer[XY]$)/,F={preventDefault:"isDefaultPrevented",
stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};b.fn.delegate=function(c,f,g){return this.each(function(d,l){n(l,f,g,c,function(d){return function(f){var t,g=b(f.target).closest(c,l).get(0);if(g)return t=b.extend(C(f),{currentTarget:g,liveFired:l}),d.apply(g,[t].concat([].slice.call(arguments,1)))}})})};b.fn.undelegate=function(b,f,g){return this.each(function(){q(this,f,g,b)})};b.fn.live=function(c,f){b(document.body).delegate(this.selector,c,f);return this};
b.fn.die=function(c,f){b(document.body).undelegate(this.selector,c,f);return this};b.fn.on=function(c,f,g){return!f||b.isFunction(f)?this.bind(c,f||g):this.delegate(f,c,g)};b.fn.off=function(c,f,g){return!f||b.isFunction(f)?this.unbind(c,f||g):this.undelegate(f,c,g)};b.fn.trigger=function(c,f){if("string"==typeof c||b.isPlainObject(c))c=b.Event(c);var g=c;if(!("defaultPrevented"in g)){g.defaultPrevented=!1;var d=g.preventDefault;g.preventDefault=function(){this.defaultPrevented=!0;d.call(this)}}c.data=
f;return this.each(function(){"dispatchEvent"in this&&this.dispatchEvent(c)})};b.fn.triggerHandler=function(c,f){var g,d;this.each(function(j,k){g=C("string"==typeof c?b.Event(c):c);g.data=f;g.target=k;b.each(l(k,c.type||c),function(b,c){d=c.proxy(g);if(g.isImmediatePropagationStopped())return!1})});return d};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(c){b.fn[c]=
function(b){return b?this.bind(c,b):this.trigger(c)}});["focus","blur"].forEach(function(c){b.fn[c]=function(b){b?this.bind(c,b):this.each(function(){try{this[c]()}catch(b){}});return this}});b.Event=function(b,f){"string"!=typeof b&&(f=b,b=f.type);var g=document.createEvent(y[b]||"Events"),d=!0;if(f)for(var l in f)"bubbles"==l?d=!!f[l]:g[l]=f[l];g.initEvent(b,d,!0,null,null,null,null,null,null,null,null,null,null,null,null);g.isDefaultPrevented=function(){return this.defaultPrevented};return g}})(Zepto);
(function(b){function k(b){var j=this.os={},k=this.browser={},n=b.match(/WebKit\/([\d.]+)/),q=b.match(/(Android)\s+([\d.]+)/),C=b.match(/(iPad).*OS\s([\d_]+)/),p=!C&&b.match(/(iPhone\sOS)\s([\d_]+)/),r=b.match(/(webOS|hpwOS)[\s\/]([\d.]+)/),y=r&&b.match(/TouchPad/),z=b.match(/Kindle\/([\d.]+)/),A=b.match(/Silk\/([\d._]+)/),x=b.match(/(BlackBerry).*Version\/([\d.]+)/),u=b.match(/(BB10).*Version\/([\d.]+)/),F=b.match(/(RIM\sTablet\sOS)\s([\d.]+)/),c=b.match(/PlayBook/),f=b.match(/Chrome\/([\d.]+)/)||
b.match(/CriOS\/([\d.]+)/),g=b.match(/Firefox\/([\d.]+)/);if(k.webkit=!!n)k.version=n[1];q&&(j.android=!0,j.version=q[2]);p&&(j.ios=j.iphone=!0,j.version=p[2].replace(/_/g,"."));C&&(j.ios=j.ipad=!0,j.version=C[2].replace(/_/g,"."));r&&(j.webos=!0,j.version=r[2]);y&&(j.touchpad=!0);x&&(j.blackberry=!0,j.version=x[2]);u&&(j.bb10=!0,j.version=u[2]);F&&(j.rimtabletos=!0,j.version=F[2]);c&&(k.playbook=!0);z&&(j.kindle=!0,j.version=z[1]);A&&(k.silk=!0,k.version=A[1]);!A&&(j.android&&b.match(/Kindle Fire/))&&
(k.silk=!0);f&&(k.chrome=!0,k.version=f[1]);g&&(k.firefox=!0,k.version=g[1]);j.tablet=!(!C&&!c&&!(q&&!b.match(/Mobile/)||g&&b.match(/Tablet/)));j.phone=!(j.tablet||!q&&!p&&!r&&!x&&!u&&!(f&&b.match(/Android/)||f&&b.match(/CriOS\/([\d.]+)/)||g&&b.match(/Mobile/)))}k.call(b,navigator.userAgent);b.__detect=k})(Zepto);
(function(b,k){function l(b){return b.toLowerCase()}var j="",m,n=window.document.createElement("div"),q=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i,C,p,r,y,z,A,x,u={};b.each({Webkit:"webkit",Moz:"",O:"o",ms:"MS"},function(b,c){if(n.style[b+"TransitionProperty"]!==k)return j="-"+l(b)+"-",m=c,!1});C=j+"transform";u[p=j+"transition-property"]=u[r=j+"transition-duration"]=u[y=j+"transition-timing-function"]=u[z=j+"animation-name"]=u[A=j+"animation-duration"]=u[x=j+"animation-timing-function"]=
"";b.fx={off:m===k&&n.style.transitionProperty===k,speeds:{_default:400,fast:200,slow:600},cssPrefix:j,transitionEnd:m?m+"TransitionEnd":l("TransitionEnd"),animationEnd:m?m+"AnimationEnd":l("AnimationEnd")};b.fn.animate=function(k,c,f,g){b.isPlainObject(c)&&(f=c.easing,g=c.complete,c=c.duration);c&&(c=("number"==typeof c?c:b.fx.speeds[c]||b.fx.speeds._default)/1E3);return this.anim(k,c,f,g)};b.fn.anim=function(j,c,f,g){var d,m={},n,w="",t=this,B,G=b.fx.transitionEnd;c===k&&(c=0.4);b.fx.off&&(c=0);
if("string"==typeof j)m[z]=j,m[A]=c+"s",m[x]=f||"linear",G=b.fx.animationEnd;else{n=[];for(d in j)q.test(d)?w+=d+"("+j[d]+") ":(m[d]=j[d],n.push(l(d.replace(/([a-z])([A-Z])/,"$1-$2"))));w&&(m[C]=w,n.push(C));0<c&&"object"===typeof j&&(m[p]=n.join(", "),m[r]=c+"s",m[y]=f||"linear")}B=function(d){if("undefined"!==typeof d){if(d.target!==d.currentTarget)return;b(d.target).unbind(G,B)}b(this).css(u);g&&g.call(this)};0<c&&this.bind(G,B);this.size()&&this.get(0).clientLeft;this.css(m);0>=c&&setTimeout(function(){t.each(function(){B.call(this)})},
0);return this};n=null})(Zepto);
(function(b){function k(d,c,f,g){if(d.global)return d=c||A,f=b.Event(f),b(d).trigger(f,g),!f.defaultPrevented}function l(b,d){var c=d.context;if(!1===d.beforeSend.call(c,b,d)||!1===k(d,c,"ajaxBeforeSend",[b,d]))return!1;k(d,c,"ajaxSend",[b,d])}function j(b,d,c){var f=c.context;c.success.call(f,b,"success",d);k(c,f,"ajaxSuccess",[d,c,b]);n("success",d,c)}function m(b,d,c,f){var g=f.context;f.error.call(g,c,d,b);k(f,g,"ajaxError",[c,f,b]);n(d,c,f)}function n(d,c,f){var g=f.context;f.complete.call(g,
c,d);k(f,g,"ajaxComplete",[c,f]);f.global&&!--b.active&&k(f,null,"ajaxStop")}function q(){}function C(b){b&&(b=b.split(";",2)[0]);return b&&(b==d?"html":b==g?"json":c.test(b)?"script":f.test(b)&&"xml")||"text"}function p(b,d){return(b+"&"+d).replace(/[&?]{1,2}/,"?")}function r(d,c,f,g){var j=!b.isFunction(c);return{url:d,data:j?c:void 0,success:!j?c:b.isFunction(f)?f:void 0,dataType:j?g||f:f}}function y(d,c,f,g){var j,k=b.isArray(c);b.each(c,function(c,t){j=b.type(t);g&&(c=f?g:g+"["+(k?"":c)+"]");
!g&&k?d.add(t.name,t.value):"array"==j||!f&&"object"==j?y(d,t,f,c):d.add(c,t)})}var z=0,A=window.document,x,u,F=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,c=/^(?:text|application)\/javascript/i,f=/^(?:text|application)\/xml/i,g="application/json",d="text/html",E=/^\s*$/;b.active=0;b.ajaxJSONP=function(d){if(!("type"in d))return b.ajax(d);var c="jsonp"+ ++z,f=A.createElement("script"),g=function(){clearTimeout(p);b(f).remove();delete window[c]},k=function(b){g();if(!b||"timeout"==b)window[c]=
q;m(null,b||"abort",n,d)},n={abort:k},p;if(!1===l(n,d))return k("abort"),!1;window[c]=function(b){g();j(b,n,d)};f.onerror=function(){k("error")};f.src=d.url.replace(/=\?/,"="+c);b("head").append(f);0<d.timeout&&(p=setTimeout(function(){k("timeout")},d.timeout));return n};b.ajaxSettings={type:"GET",beforeSend:q,success:q,error:q,complete:q,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript",json:g,xml:"application/xml, text/xml",
html:d,text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};b.ajax=function(d){var c=b.extend({},d||{});for(x in b.ajaxSettings)void 0===c[x]&&(c[x]=b.ajaxSettings[x]);c.global&&0===b.active++&&k(c,null,"ajaxStart");c.crossDomain||(c.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(c.url)&&RegExp.$2!=window.location.host);c.url||(c.url=window.location.toString());c.processData&&(c.data&&"string"!=b.type(c.data))&&(c.data=b.param(c.data,c.traditional));if(c.data&&(!c.type||"GET"==c.type.toUpperCase()))c.url=
p(c.url,c.data);!1===c.cache&&(c.url=p(c.url,"_="+Date.now()));var f=c.dataType;d=/=\?/.test(c.url);if("jsonp"==f||d)return d||(c.url=p(c.url,"callback=?")),b.ajaxJSONP(c);d=c.accepts[f];var g={},n=/^([\w-]+:)\/\//.test(c.url)?RegExp.$1:window.location.protocol,s=c.xhr(),r;c.crossDomain||(g["X-Requested-With"]="XMLHttpRequest");d&&(g.Accept=d,-1<d.indexOf(",")&&(d=d.split(",",2)[0]),s.overrideMimeType&&s.overrideMimeType(d));if(c.contentType||!1!==c.contentType&&c.data&&"GET"!=c.type.toUpperCase())g["Content-Type"]=
c.contentType||"application/x-www-form-urlencoded";c.headers=b.extend(g,c.headers||{});s.onreadystatechange=function(){if(4==s.readyState){s.onreadystatechange=q;clearTimeout(r);var d,g=!1;if(200<=s.status&&300>s.status||304==s.status||0==s.status&&"file:"==n){f=f||C(s.getResponseHeader("content-type"));d=s.responseText;try{"script"==f?(0,eval)(d):"xml"==f?d=s.responseXML:"json"==f&&(d=E.test(d)?null:b.parseJSON(d))}catch(k){g=k}g?m(g,"parsererror",s,c):j(d,s,c)}else m(null,s.status?"error":"abort",
s,c)}};s.open(c.type,c.url,"async"in c?c.async:!0);for(u in c.headers)s.setRequestHeader(u,c.headers[u]);if(!1===l(s,c))return s.abort(),!1;0<c.timeout&&(r=setTimeout(function(){s.onreadystatechange=q;s.abort();m(null,"timeout",s,c)},c.timeout));s.send(c.data?c.data:null);return s};b.get=function(c,d,f,g){return b.ajax(r.apply(null,arguments))};b.post=function(c,d,f,g){var j=r.apply(null,arguments);j.type="POST";return b.ajax(j)};b.getJSON=function(c,d,f){var g=r.apply(null,arguments);g.dataType=
"json";return b.ajax(g)};b.fn.load=function(c,d,f){if(!this.length)return this;var g=this,j=c.split(/\s/),k;c=r(c,d,f);var l=c.success;1<j.length&&(c.url=j[0],k=j[1]);c.success=function(c){g.html(k?b("<div>").html(c.replace(F,"")).find(k):c);l&&l.apply(g,arguments)};b.ajax(c);return this};var D=encodeURIComponent;b.param=function(b,c){var d=[];d.add=function(b,c){this.push(D(b)+"="+D(c))};y(d,b,c);return d.join("&").replace(/%20/g,"+")}})(Zepto);
(function(b){b.fn.serializeArray=function(){var k=[],l;b(Array.prototype.slice.call(this.get(0).elements)).each(function(){l=b(this);var j=l.attr("type");"fieldset"!=this.nodeName.toLowerCase()&&(!this.disabled&&"submit"!=j&&"reset"!=j&&"button"!=j&&("radio"!=j&&"checkbox"!=j||this.checked))&&k.push({name:l.attr("name"),value:l.val()})});return k};b.fn.serialize=function(){var b=[];this.serializeArray().forEach(function(l){b.push(encodeURIComponent(l.name)+"="+encodeURIComponent(l.value))});return b.join("&")};
b.fn.submit=function(k){k?this.bind("submit",k):this.length&&(k=b.Event("submit"),this.eq(0).trigger(k),k.defaultPrevented||this.get(0).submit());return this}})(Zepto);(function(b){b.fn.end=function(){return this.prevObject||b()};b.fn.andSelf=function(){return this.add(this.prevObject||b())};"filter add not eq first last find closest parents parent children siblings".split(" ").forEach(function(k){var l=b.fn[k];b.fn[k]=function(){var b=l.apply(this,arguments);b.prevObject=this;return b}})})(Zepto);